### ISSUE TITLE
Can not connect and no tunfd_file file

### ISSUE THREAD

**Issue by IHNEL** [staf621/ki4a#27]
Hi, I always got this error and never connect successfully:
>java.io.IOException: No such file or directory
>Unable to connect to localSocksFile [/data/data/com.gluu.life/ki4a/tunfd_file]

Any recommendation?

**Comment by IHNEL** [comment]
@staf621 could you please have a look?

**Comment by staf621** [comment]
Sorry for the late reply, I've been quite busy and I'm only giving partial support to this project.

Could you please send me an email with Application's Log?

Are you using any custom rom? From the error it looks like you don't have support for TUN/TAP.

Thanks for reporting this issue

--------------------------------------------------------------------------------------------
Update:

Sorry, I just noticed that you renamed the project (com.gluu.life), I have already seen this problem before, it's related an issue with the binaries pointing to a different tunfd file.

Please send me an email and I can help you to work around this issue patching the binaries or re-compiling them.

Regards

**Comment by IHNEL** [comment]
Hi @staf621 
Thank you for your replies.
I already sent you an email and looking forward to get your help.

Thank you very much 💯

**Comment by IHNEL** [comment]
Thank you for your help @staf621 
I can resolve this issue now.

**Comment by hkhoshraftar2** [comment]
hi
could you please help me for this problem.
my email: hkhoshraftar@gmail.com

**Comment by mohsensaremi** [comment]
@IHNEL did you receive any email from @staf621 ?

I need the binary files for package name `com.vpn.smartconnect`
my email: mohsen.sareminia@gmail.com

**Comment by slr560** [comment]
hi
I need the binary files for package name `ir.darabifard.tunnel`
email: m.darabifard@gmail.com

**Comment by mohsensaremi** [comment]
@slr560 hello friend
I am the one who gave you the project in https://ponisha.ir
thanks for help :|
