### ISSUE TITLE
Cannot verify connectivity

### ISSUE THREAD

**Issue by MattiasC** [staf621/ki4a#9]
I can log in with another ssh client on the same device and ping google.com

_Log with server and user name redacted_
[ki4a.txt](https://github.com/staf621/ki4a/files/728836/ki4a.txt)

Nexus 5X with Android 7.1.1

**Comment by igorm84** [comment]
Try to change the DNS, or check the connectivity of your SSH server.

**Comment by MattiasC** [comment]
I forgot about this, sorry. Have switched to a new phone and VPN instead, so no possibility to test.
